using System.ComponentModel;
using Spectre.Console;
using Spectre.Console.Cli;
using SteadyCron.Cli.Output;

namespace SteadyCron.Cli.Commands;

public sealed class InitSettings : CommandSettings
{
    [CommandOption("--terraform")]
    [Description("Generate a Terraform HCL boilerplate instead of YAML.")]
    public bool Terraform { get; set; }

    [CommandOption("-o|--output-file <PATH>")]
    [Description("Write the boilerplate to a file instead of printing to stdout.")]
    public string? OutputFile { get; set; }
}

/// <summary>`steadycron init` — generates a fully documented boilerplate manifest covering every SteadyCron feature.</summary>
public sealed class InitCommand : Command<InitSettings>
{
    public override int Execute(CommandContext context, InitSettings settings)
    {
        var content = settings.Terraform ? TerraformBoilerplate : YamlBoilerplate;

        if (settings.OutputFile is null)
        {
            Console.Write(content);
            return ExitCodes.Ok;
        }

        if (File.Exists(settings.OutputFile))
        {
            AnsiConsole.MarkupLineInterpolated(
                $"[red]✗[/] File already exists: {settings.OutputFile}. Delete it or choose a different path.");
            return ExitCodes.Error;
        }

        File.WriteAllText(settings.OutputFile, content);

        if (settings.Terraform)
        {
            AnsiConsole.MarkupLineInterpolated(
                $"[green]✓[/] Terraform boilerplate written to [bold]{settings.OutputFile}[/]");
            AnsiConsole.MarkupLine(
                "Run [bold]terraform init && terraform plan[/] to preview, then [bold]terraform apply[/] to provision.");
        }
        else
        {
            AnsiConsole.MarkupLineInterpolated(
                $"[green]✓[/] YAML manifest written to [bold]{settings.OutputFile}[/]");
            AnsiConsole.MarkupLine(
                "Run [bold]steadycron plan steadycron.yaml[/] to preview, then [bold]steadycron apply steadycron.yaml[/] to apply.");
        }

        return ExitCodes.Ok;
    }

    private const string YamlBoilerplate =
        """
        # steadycron.yaml — generated by `steadycron init`
        #
        # This file covers every SteadyCron manifest feature. Use it as a starting point,
        # delete the sections you don't need, then run:
        #
        #   steadycron plan steadycron.yaml    # preview what will change (no writes)
        #   steadycron apply steadycron.yaml   # apply changes to your account
        #
        # To validate the file locally without hitting the API:
        #   steadycron validate steadycron.yaml

        version: 2

        # namespace scopes all resource keys in this file. Required when using --prune
        # (to avoid deleting resources from other namespaces) and when merging multiple
        # manifest files with `steadycron apply ./manifests/`.
        namespace: my-project

        # ── Template Variables ────────────────────────────────────────────────────────
        # Template variables let you keep secrets and environment-specific values out
        # of the manifest. Reference them in any job field with {{VARIABLE_NAME}}.
        #
        # Variable values can themselves read from the local environment at apply-time
        # using ${ENV_VAR} syntax, or from an --env-file:
        #   steadycron apply --env-file secrets.env steadycron.yaml
        #
        # Secret values are write-only in the API — they cannot be read back on export.
        # When you run `steadycron export`, secret values are replaced with ${PLACEHOLDER}
        # and must be re-supplied via --env-file or environment variables.
        variables:
          - name: API_TOKEN
            value: ${API_TOKEN}          # reads the API_TOKEN environment variable at apply-time
          - name: WEBHOOK_SECRET
            value: ${WEBHOOK_SECRET}     # reads the WEBHOOK_SECRET environment variable at apply-time

        # ── Tags ──────────────────────────────────────────────────────────────────────
        # Tags let you group and filter jobs on the dashboard and in CLI queries.
        # Reference a tag in a job as a "key:value" string (see jobs section below).
        #
        # Valid colors: red, orange, amber, yellow, lime, green, teal, cyan, blue,
        #               indigo, violet, purple, pink, rose, slate, gray, zinc.
        tags:
          - key: env
            value: production
            color: green
          - key: env
            value: staging
            color: yellow
          - key: team
            value: backend              # color is optional

        # ── Alert Channels ────────────────────────────────────────────────────────────
        # Alert channels define WHERE notifications go when a rule fires.
        # Reference a channel by its `name` in a job's `rules` section.
        channels:

          # Email channel — delivers to a single address.
          - name: ops-email
            kind: email
            config:
              to: ops@example.com

          # Slack channel — posts to a channel via an incoming webhook URL.
          - name: ops-slack
            kind: slack
            config:
              webhook_url: "{{WEBHOOK_SECRET}}"   # references the template variable defined above

          # Generic webhook — sends a POST (or any method) to any URL.
          # - name: ops-webhook
          #   kind: webhook
          #   config:
          #     url: https://example.com/hooks/steadycron
          #     method: POST              # GET | POST | PUT | PATCH | DELETE

          # Discord — delivers via a Discord webhook URL.
          # - name: ops-discord
          #   kind: discord
          #   config:
          #     webhook_url: https://discord.com/api/webhooks/123/abc

          # Telegram — sends a message via a bot to a chat or channel.
          # - name: ops-telegram
          #   kind: telegram
          #   config:
          #     bot_token: "{{TELEGRAM_BOT_TOKEN}}"
          #     chat_id: "123456789"

        # ── Jobs ──────────────────────────────────────────────────────────────────────
        jobs:

          # ── HTTP job ──────────────────────────────────────────────────────────────
          # SteadyCron calls this URL on the given schedule and alerts if it fails.
          # A job succeeds when it returns a 2xx status within the timeout.
          - id: daily-report            # stable reconciliation key — never change this
            name: Daily report          # human-readable display name (may be renamed freely)
            kind: http                  # http (default) | heartbeat

            description: Generates the overnight analytics report and emails a summary.

            # Runbook — where to look when this job fails.
            runbook_url: https://wiki.example.com/runbooks/daily-report
            runbook_notes: |
              1. Check the data-pipeline Grafana dashboard for upstream failures.
              2. Re-trigger manually via: curl -X POST -H "Authorization: Bearer {{API_TOKEN}}" https://api.example.com/report

            # ── Schedule ────────────────────────────────────────────────────────────
            # Use `schedule` (5-field cron) OR `interval` (seconds) — not both.
            schedule: "0 8 * * 1-5"     # every weekday at 08:00 in the job's timezone
            # interval: 3600            # alternative: fire every 3600 seconds (1 hour)
            timezone: Europe/Berlin     # IANA timezone. Defaults to UTC when omitted.
            paused: false               # set true to declare the job without activating it

            # ── HTTP settings ──────────────────────────────────────────────────────
            method: POST                # GET (default) | POST | PUT | PATCH | DELETE | HEAD
            url: https://api.example.com/jobs/daily-report
            headers:
              Authorization: "Bearer {{API_TOKEN}}"   # {{VAR}} = SteadyCron template variable
              Content-Type: application/json
            body: '{"trigger": "scheduled"}'

            # ── Timeout and retries ────────────────────────────────────────────────
            timeout: 30                 # seconds before the request is abandoned
            retries: 2                  # retry count on failure (0 = no retries)
            retry_backoff: 10           # seconds between retries
            retry_on_timeout: true      # also retry when the request times out
            retry_on_status:            # retry on these HTTP status codes
              - 500
              - 502
              - 503
              # empty list (default) means any non-2xx status triggers a retry
            skip_if_running: false      # set true to skip a scheduled fire if the previous run is still active

            # misfire_policy: what to do when a scheduled fire is missed entirely
            # (e.g. because the job was paused, or the system was briefly down).
            #   do_nothing:    skip the missed fire — safe for idempotent workloads (default)
            #   fire_once_now: run once immediately when the job recovers
            misfire_policy: do_nothing

            tags:
              - env:production
              - team:backend

            # ── Alert rules ────────────────────────────────────────────────────────
            # Rules define WHEN to alert and on WHICH channel.
            # Available triggers:
            #   on_failure          — fires each time an execution fails
            #   on_n_consecutive    — fires after N consecutive failures (requires params.threshold)
            #   on_missed_heartbeat — fires when a heartbeat check-in is overdue
            #   on_recovery         — fires once when the job recovers after a failure/miss
            rules:
              - channel: ops-slack          # channel name defined in the channels section above
                trigger: on_failure
                severity: p2               # p1 (critical) | p2 (default) | p3 (low)
                dedup_window_seconds: 300  # suppress repeated alerts within this window (5 min)

              # Alert after 3 consecutive failures rather than on every single failure.
              # - channel: ops-email
              #   trigger: on_n_consecutive
              #   severity: p1
              #   params:
              #     threshold: 3

              # Fire once when the job succeeds again after a period of failure.
              - channel: ops-slack
                trigger: on_recovery
                severity: p3

          # ── Heartbeat monitor ──────────────────────────────────────────────────────
          # YOUR code sends a ping to SteadyCron on each successful run.
          # SteadyCron alerts if no ping arrives within the expected window.
          #
          # Obtain the ping URL after applying:
          #   steadycron jobs get nightly-backup
          - id: nightly-backup
            name: Nightly backup
            kind: heartbeat

            description: Database backup that runs via the production server's cron daemon.
            runbook_url: https://wiki.example.com/runbooks/nightly-backup

            # Use `schedule` (cron) OR `interval` (seconds) — not both.
            schedule: "0 2 * * *"       # expect a ping every night at 02:00
            # interval: 86400           # alternative: expect a ping every 24 hours
            timezone: UTC
            paused: false

            # grace: seconds of extra time allowed after the expected window closes before
            # SteadyCron triggers an alert. Absorbs normal scheduling jitter.
            grace: 600                  # 10-minute grace period

            # stuck_run_detection: alert when a run starts (via the /start ping) but never
            # completes (no /finish or /fail ping within max_run_duration seconds).
            stuck_run_detection: true

            # max_run_duration: maximum expected runtime in seconds.
            # Only meaningful when stuck_run_detection is true.
            max_run_duration: 3600      # 1 hour

            tags:
              - env:production

            rules:
              - channel: ops-email
                trigger: on_missed_heartbeat
                severity: p1
                dedup_window_seconds: 3600   # at most one alert per hour

              - channel: ops-email
                trigger: on_recovery
                severity: p3

        # ── Delivery Shaping ──────────────────────────────────────────────────────────
        # Account-level throttles applied across all jobs. Useful when many jobs fire at
        # the same second and you want to smooth out the load.
        # Uncomment to enable.
        # shaping:
        #   max_concurrent_jobs: 20     # cap the number of simultaneously running HTTP jobs
        #   max_jobs_per_minute: 60     # rate-limit execution starts across the whole account

        """;

    private const string TerraformBoilerplate =
        """
        # steadycron.tf — generated by `steadycron init --terraform`
        #
        # This file covers every SteadyCron Terraform resource. Use it as a starting
        # point and delete the blocks you don't need.
        #
        # To take ownership of existing resources without recreating them, run:
        #   steadycron export --format terraform -o existing.tf
        # That command generates import {} blocks alongside each resource.
        #
        # Apply this file:
        #   terraform init
        #   terraform plan
        #   terraform apply

        terraform {
          required_version = ">= 1.5"
          required_providers {
            steadycron = {
              source  = "steadycron/steadycron"
              version = "~> 1.0"
            }
          }
        }

        # Set the STEADYCRON_API_KEY environment variable (recommended), or pass api_key
        # explicitly:  provider "steadycron" { api_key = var.steadycron_api_key }
        provider "steadycron" {}

        # ── Input variables (sensitive) ───────────────────────────────────────────────
        # Supply values via terraform.tfvars or -var flags:
        #   terraform apply -var='api_token=sk_live_...' -var='slack_webhook_url=https://...'
        variable "api_token" {
          description = "Bearer token for the internal API, stored as a SteadyCron template variable."
          sensitive   = true
        }

        variable "slack_webhook_url" {
          description = "Slack incoming webhook URL."
          sensitive   = true
        }

        # ── Template variables ────────────────────────────────────────────────────────
        # Template variables are referenced in job URLs, headers, and bodies as {{NAME}}.
        # Their values are write-only in the API — they cannot be read back after creation.
        resource "steadycron_template_variable" "api_token" {
          name  = "API_TOKEN"
          value = var.api_token
        }

        # ── Tags ──────────────────────────────────────────────────────────────────────
        # Valid colors: red, orange, amber, yellow, lime, green, teal, cyan, blue,
        #               indigo, violet, purple, pink, rose, slate, gray, zinc.
        resource "steadycron_tag" "env_production" {
          key   = "env"
          value = "production"
          color = "green"
        }

        resource "steadycron_tag" "env_staging" {
          key   = "env"
          value = "staging"
          color = "yellow"
        }

        resource "steadycron_tag" "team_backend" {
          key   = "team"
          value = "backend"
          # color is optional
        }

        # ── Alert channels ────────────────────────────────────────────────────────────
        # Each channel kind uses its own set of attributes.
        # Run `steadycron export --format terraform` to confirm attribute names for your
        # existing channels.

        # Email channel
        resource "steadycron_alert_channel" "ops_email" {
          name     = "ops-email"
          kind     = "email"
          email_to = "ops@example.com"
        }

        # Slack channel
        resource "steadycron_alert_channel" "ops_slack" {
          name              = "ops-slack"
          kind              = "slack"
          slack_webhook_url = var.slack_webhook_url
        }

        # Generic webhook channel
        # resource "steadycron_alert_channel" "ops_webhook" {
        #   name        = "ops-webhook"
        #   kind        = "webhook"
        #   webhook_url = "https://example.com/hooks/steadycron"
        #   method      = "POST"          # optional, defaults to POST
        # }

        # Discord channel
        # resource "steadycron_alert_channel" "ops_discord" {
        #   name                 = "ops-discord"
        #   kind                 = "discord"
        #   discord_webhook_url  = "https://discord.com/api/webhooks/123/abc"
        # }

        # Telegram channel
        # variable "telegram_bot_token" {
        #   sensitive = true
        # }
        # resource "steadycron_alert_channel" "ops_telegram" {
        #   name               = "ops-telegram"
        #   kind               = "telegram"
        #   telegram_bot_token = var.telegram_bot_token
        #   telegram_chat_id   = "123456789"
        # }

        # ── HTTP job ──────────────────────────────────────────────────────────────────
        # SteadyCron calls this URL on schedule and alerts if it fails.
        resource "steadycron_http_job" "daily_report" {
          name = "Daily report"
          key  = "daily-report"   # stable reconciliation key — never change this

          method = "POST"
          url    = "https://api.example.com/jobs/daily-report"

          # Use cron_expression (5-field) OR interval_seconds — not both.
          cron_expression = "0 8 * * 1-5"   # every weekday at 08:00
          # interval_seconds = 3600          # alternative: every 3600 seconds

          timezone        = "Europe/Berlin"  # IANA timezone. UTC if omitted.
          timeout_seconds = 30

          headers = {
            "Authorization" = "Bearer {{API_TOKEN}}"   # {{VAR}} = template variable reference
            "Content-Type"  = "application/json"
          }

          body = jsonencode({
            trigger = "scheduled"
          })

          # skip_if_running = true    # skip a scheduled fire if the previous run is still active
          # paused          = false   # set true to define without activating

          tags = [
            steadycron_tag.env_production.id,
            steadycron_tag.team_backend.id,
          ]
        }

        # ── Heartbeat monitor ─────────────────────────────────────────────────────────
        # YOUR code pings SteadyCron on each successful run.
        # SteadyCron alerts if no ping arrives within the expected window + grace period.
        resource "steadycron_heartbeat_monitor" "nightly_backup" {
          name = "Nightly backup"
          key  = "nightly-backup"

          # Use cron_expression OR interval_seconds — not both.
          cron_expression = "0 2 * * *"      # expect a ping every night at 02:00
          # interval_seconds = 86400         # alternative: every 24 hours

          timezone                 = "UTC"
          grace_seconds            = 600     # 10-minute window after the expected ping time
          max_run_duration_seconds = 3600    # alert if a started run doesn't complete within 1 h

          tags = [
            steadycron_tag.env_production.id,
          ]
        }

        # ── Alert rules ───────────────────────────────────────────────────────────────
        # Rules define WHEN to notify and on WHICH channel.
        # Available triggers:
        #   on_failure          — fires each time an execution fails
        #   on_n_consecutive    — fires after N consecutive failures (requires threshold)
        #   on_missed_heartbeat — fires when a heartbeat check-in is overdue
        #   on_recovery         — fires once when the job recovers

        resource "steadycron_alert_rule" "daily_report_on_failure" {
          job_id               = steadycron_http_job.daily_report.id
          channel_id           = steadycron_alert_channel.ops_slack.id
          trigger              = "on_failure"
          dedup_window_seconds = 300   # suppress repeated alerts within 5 minutes
        }

        # Alert after 3 consecutive failures rather than on every single failure.
        # resource "steadycron_alert_rule" "daily_report_on_n_consecutive" {
        #   job_id     = steadycron_http_job.daily_report.id
        #   channel_id = steadycron_alert_channel.ops_email.id
        #   trigger    = "on_n_consecutive"
        #   threshold  = 3
        # }

        resource "steadycron_alert_rule" "daily_report_on_recovery" {
          job_id     = steadycron_http_job.daily_report.id
          channel_id = steadycron_alert_channel.ops_slack.id
          trigger    = "on_recovery"
        }

        resource "steadycron_alert_rule" "nightly_backup_on_missed_heartbeat" {
          job_id               = steadycron_heartbeat_monitor.nightly_backup.id
          channel_id           = steadycron_alert_channel.ops_email.id
          trigger              = "on_missed_heartbeat"
          dedup_window_seconds = 3600   # at most one alert per hour
        }

        resource "steadycron_alert_rule" "nightly_backup_on_recovery" {
          job_id     = steadycron_heartbeat_monitor.nightly_backup.id
          channel_id = steadycron_alert_channel.ops_email.id
          trigger    = "on_recovery"
        }

        """;
}
