<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <!-- xUnit analyzers emit suggestions we don't want to fail the build over. -->
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Spectre.Console.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/SteadyCron.Cli/SteadyCron.Cli.csproj" />
  </ItemGroup>

</Project>
